### ISSUE TITLE
Output Filter

### ISSUE THREAD

**Issue by CQuin042** [RHESSys/RHESSysIOinR#17]
Able to run RHESSys within R environment but unable to run with output filtering

when included filter is used error that returns is 
"Error: syntax error, unexpected DOT, expecting PATH_SPEC or FILENAME_SPEC, for token: |.|
construct_output_filter failed with error: output_filter_parser returned with an error."

when a custom filter that was created is used what is returned is 
"Error: syntax error, unexpected IDENTIFIER, expecting PATH_SPEC or FILENAME_SPEC, for token: |test|
construct_output_filter failed with error: output_filter_parser returned with an error."

output_path is "test/" for the custom filter but other combinations of "test","/test/","./test/" have been applied. 

RHESSys is being run via Windows in R

**Comment by wburke24** [comment]
The output filter path parser is a kinda finicky, it can have issues if you have a period/dot anywhere in the path, since i think it assumes it will only be used to indicate current folder. I also remember it being weird with trailing forward slashes. I've had most consistent success with no punctuation, eg just "test" for the output location, assuming that folder exists. I also know there was discussion at some point of fixing the parser so change may have been/will be made. Sorry not really fixing the issue, hopefully you can sort it out.

**Comment by CQuin042** [comment]
I believe that the issue has been resolved by updating RHESSysIOinR to the latest version. The output path of "test" is currently working without issue.

**Comment by CQuin042** [comment]
I believe that the issue has been resolved by updating RHESSysIOinR to the latest version. The output path of "test" is currently working without issue.
